name: online_store
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  uuid: ^2.2.2
  cached_network_image: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Lobster
      fonts:
      - asset: assets/fonts/Lobster.ttf
  assets:
    - assets/images/google_signin.png
    - assets/images/continue_with_fb.png